<a href="https://colab.research.google.com/github/DebjitHore/Jovian_ML_DataAnalysiswithPython/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('numpy-array-operations')
jovian.set_colab_id('1klKhY_bbH7xzDyfgdhOzrJArcLlERsaK')

     |████████████████████████████████| 71kB 7.7MB/s 


In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [4]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations


'https://jovian.ai/debjithore/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.arange  # (change this)
function2 = np.reshape
function3 = np.sort
function4 = np.vstack
function5 = np.equal

## Function 1 - np.arange/np.linspace (comparing subtle differences)

**np.arange** Return evenly spaced values within a given interval. Values are generated within the half-open interval ``[start, stop)`` (in other words, the interval including `start` but excluding `stop`). For integer arguments the function is equivalent to the Python built-in `range` function, but returns an ndarray rather than a list.

**np.linspace** Return evenly spaced numbers over a specified interval. Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`]. The endpoint of the interval can optionally be excluded.

In [11]:
arr1= np.arange(0, 56, 11)

print(arr1)

[ 0 11 22 33 44 55] [ 0. 11. 22. 33. 44. 55.]


Generating a 1D array between `start` and `stop` with a spacing of `step` between each member of the array

In [14]:
arr1= np.arange(0, 101, 10)
arr1

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

The function breaks when the stop value is a non-integer type



In [21]:
arr1= np.arange(0, '9.5', 2)
arr1

TypeError: ignored

The function breaks when the stop value is a non-integer type, so the start,stop and step values should always be integer or float type

Use function when you need to generate a 1D array

In [22]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations


'https://jovian.ai/debjithore/numpy-array-operations'

## Function 2 - np.reshape

Gives a new shape to an array without changing its data.

In [26]:
print(arr1.reshape((5,1)))

[[0.]
 [2.]
 [4.]
 [6.]
 [8.]]


Creating a random 1D array of 25 elements and then reshaping it to a (5,5) 2D array.

In [27]:
arr= np.random.randint(0, 15, 25)
print(arr.reshape((5,5)))

[[ 6  4  3 12  9]
 [14 14  6  7  3]
 [ 2 12  3 10 14]
 [ 0  8  4 11  5]
 [ 5 14  2  6  0]]


Error scenario of np.reshape

In [28]:
arr.reshape((5,4))

ValueError: ignored

The `reshape` function breaks when the number of elements in original array and the reshaped array are not equal

Use it to reshape arrays.

In [29]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations


'https://jovian.ai/debjithore/numpy-array-operations'

## Function 3 - np.sort

Return a sorted copy of an array.


In [32]:
arr= arr.reshape((5,5))
np.sort(arr, axis=0)

array([[ 0,  4,  2,  6,  0],
       [ 2,  8,  3,  7,  3],
       [ 5, 12,  3, 10,  5],
       [ 6, 14,  4, 11,  9],
       [14, 14,  6, 12, 14]])

Sorting a 1D array.

In [34]:
np.sort(np.random.randint(0,100,25))

array([ 1,  4,  5,  9, 14, 20, 23, 28, 29, 32, 33, 33, 37, 43, 49, 56, 68,
       69, 77, 78, 79, 88, 89, 89, 90])

Trying to sort an array with integer and string elements

In [36]:
np.array([1,2,3,'a', 'b'], dtype=object).sort()

TypeError: ignored

Function breaks when you try to sort a mixed data type array

Use to sort an array, the algorithm used to sort can also be chosen.

In [37]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations


'https://jovian.ai/debjithore/numpy-array-operations'

## Function 4 - np.vstack

Used to stack the arrays row-wise

In [39]:
# Example 1 - working
arr1 = np.array([
                 [1,2,3,4],
                 [5,6,7,8]
])
arr2= np.array([
                [7,8,9,10],
                [11,12,13,14]
])
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

Stacking the arrays in reverse order

In [40]:
np.vstack((arr2,arr1))

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

Breaks when array sizes not compatible 

In [42]:
arr2= np.array([
                [7,8,9],
                [11,12,13]
])
np.vstack((arr2,arr1))

ValueError: ignored

Breaks because array sizes are not compatible for a vstack operation, makes sure they have same number of columns for a vstack

Use to stack arrays row-wise

In [43]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations


'https://jovian.ai/debjithore/numpy-array-operations'

## Function 5 - np.equal

Return (x1 == x2) element-wise.

In [45]:
x1= np.array([1,2,3,4])
x2= np.array([5,6,7,8])
np.equal(x1,x2)

array([False, False, False, False])

Comparing two arrays of dissimilar sizes but that are broadcastable

In [48]:
x1= np.array([1,2,3,4])
x2= np.array([
              [1,2,3,4],
              [5,6,7,8]
])
np.equal(x1,x2)

array([[ True,  True,  True,  True],
       [False, False, False, False]])

Breaks when array sizes are not comaptible

In [49]:
x1= np.array([1,2,3,4])
x2= np.array([5,6,7])
np.equal(x1,x2)

ValueError: ignored

Breaks because array sizes are not equal and neither can be broadcast onto each other.

Use when trying to compare element of two compatible array sizes, elementwise

In [50]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations


'https://jovian.ai/debjithore/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [51]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations


'https://jovian.ai/debjithore/numpy-array-operations'

In [52]:
jovian.submit(assignment="zero-to-pandas-a2")

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/debjithore/numpy-array-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
